export type Mood = "뛰놀기" | "탐험하기" | "배우기" | "느긋하게";
export type Setting = "야외" | "실내+야외" | "실내";

export type PlaceProfile = {
  id: string;
  name: string;
  dataName: string;
  shortName: string;
  district: string;
  lat: number;
  lng: number;
  moods: Mood[];
  setting: Setting;
  duration: 2 | 4 | 6;
  cost: "무료" | "일부 유료";
  energy: 1 | 2 | 3;
  learning: 1 | 2 | 3;
  emoji: string;
  tagline: string;
  mission: string;
  dadTip: string;
};
export const PLACES: PlaceProfile[] = [
  {
    id: "children-grand-park",
    name: "서울어린이대공원",
    dataName: "어린이대공원",
    shortName: "어린이대공원",
    district: "광진구",
    lat: 37.5491,
    lng: 127.0814,
    moods: ["뛰놀기", "탐험하기"],
    setting: "야외",
    duration: 4,
    cost: "일부 유료",
    energy: 3,
    learning: 2,
    emoji: "🦁",
    tagline: "동물원부터 숲길까지, 실패 확률 낮은 정석 코스",
    mission: "가장 웃긴 표정의 동물 하나를 찾아 사진으로 남기기",
    dadTip: "정문보다 후문 쪽이 한결 여유롭고 아차산역 접근이 편해요.",
  },
  {
    id: "national-museum",
    name: "국립중앙박물관·용산가족공원",
    dataName: "국립중앙박물관·용산가족공원",
    shortName: "국립중앙박물관",
    district: "용산구",
    lat: 37.5228,
    lng: 126.9814,
    moods: ["배우기", "느긋하게"],
    setting: "실내+야외",
    duration: 4,
    cost: "무료",
    energy: 1,
    learning: 3,
    emoji: "🏺",
    tagline: "덥거나 비 와도 든든한 역사 탐험 베이스캠프",
    mission: "교과서에서 본 유물 하나를 직접 찾아 이름 맞히기",
    dadTip: "전시를 다 보려 하지 말고 아이가 고른 시대 한 곳만 깊게 보세요.",
  },
  {
    id: "seoul-forest",
    name: "서울숲",
    dataName: "서울숲",
    shortName: "서울숲",
    district: "성동구",
    lat: 37.5444,
    lng: 127.0374,
    moods: ["뛰놀기", "느긋하게"],
    setting: "야외",
    duration: 4,
    cost: "무료",
    energy: 3,
    learning: 1,
    emoji: "🦌",
    tagline: "자전거·사슴·넓은 잔디, 몸 쓰는 날의 1순위",
    mission: "나뭇잎 모양이 서로 다른 나무 세 종류 찾기",
    dadTip: "돗자리와 얼음물만 챙기면 체류 시간이 두 배로 늘어요.",
  },
  {
    id: "seoul-botanic",
    name: "서울식물원·마곡나루",
    dataName: "서울식물원·마곡나루역",
    shortName: "서울식물원",
    district: "강서구",
    lat: 37.5684,
    lng: 126.8351,
    moods: ["탐험하기", "배우기"],
    setting: "실내+야외",
    duration: 4,
    cost: "일부 유료",
    energy: 2,
    learning: 3,
    emoji: "🌴",
    tagline: "거대한 온실을 탐험하는 도심 속 정글 미션",
    mission: "우리 집보다 큰 잎을 가진 식물 찾아보기",
    dadTip: "한낮에는 온실부터, 해가 기울면 호수공원으로 움직이면 좋아요.",
  },
  {
    id: "north-dream-forest",
    name: "북서울꿈의숲",
    dataName: "북서울꿈의숲",
    shortName: "북서울꿈의숲",
    district: "강북구",
    lat: 37.6219,
    lng: 127.0411,
    moods: ["뛰놀기", "느긋하게"],
    setting: "야외",
    duration: 4,
    cost: "무료",
    energy: 3,
    learning: 1,
    emoji: "🌳",
    tagline: "넓고 한적해서 아이가 마음껏 뛰기 좋은 큰 공원",
    mission: "전망대에서 우리 동네 방향 찾아보기",
    dadTip: "공원이 넓으니 방문자센터와 전망대 중 한 곳을 목표로 잡으세요.",
  },
  {
    id: "world-cup-park",
    name: "월드컵공원",
    dataName: "월드컵공원",
    shortName: "월드컵공원",
    district: "마포구",
    lat: 37.5702,
    lng: 126.8842,
    moods: ["뛰놀기", "탐험하기"],
    setting: "야외",
    duration: 4,
    cost: "무료",
    energy: 3,
    learning: 2,
    emoji: "🪁",
    tagline: "바람·자전거·생태공원을 한 번에 만나는 큰 운동장",
    mission: "바람이 가장 센 장소를 몸으로 찾아보기",
    dadTip: "평화의공원만 돌아도 충분해요. 하늘공원까지 욕심내면 6시간 코스예요.",
  },
  {
    id: "olympic-park",
    name: "올림픽공원",
    dataName: "올림픽공원",
    shortName: "올림픽공원",
    district: "송파구",
    lat: 37.5194,
    lng: 127.1224,
    moods: ["뛰놀기", "탐험하기"],
    setting: "야외",
    duration: 4,
    cost: "무료",
    energy: 3,
    learning: 2,
    emoji: "🏃",
    tagline: "달리고, 자전거 타고, 조각 작품도 찾는 만능 코스",
    mission: "가장 마음에 드는 조각 작품에 새 제목 붙여주기",
    dadTip: "공연이 있는 날은 지하철역 쪽이 붐벼요. 북2문 진입이 비교적 편합니다.",
  },
  {
    id: "gwanghwamun",
    name: "광화문광장",
    dataName: "광화문광장",
    shortName: "광화문광장",
    district: "종로구",
    lat: 37.5734,
    lng: 126.9769,
    moods: ["탐험하기", "배우기"],
    setting: "야외",
    duration: 2,
    cost: "무료",
    energy: 2,
    learning: 3,
    emoji: "🧭",
    tagline: "한글·역사·도심 풍경이 이어지는 짧고 굵은 탐험",
    mission: "광장 안에서 한글 창제와 관련된 단서 세 개 찾기",
    dadTip: "교보문고나 대한민국역사박물관을 비상 실내 코스로 묶어두세요.",
  },
  {
    id: "gyeongbokgung",
    name: "경복궁",
    dataName: "경복궁",
    shortName: "경복궁",
    district: "종로구",
    lat: 37.5799,
    lng: 126.9768,
    moods: ["탐험하기", "배우기"],
    setting: "야외",
    duration: 4,
    cost: "일부 유료",
    energy: 2,
    learning: 3,
    emoji: "👑",
    tagline: "왕이 다니던 길을 직접 고르는 조선시대 타임슬립",
    mission: "임금이라면 살고 싶은 전각 하나를 골라 이유 말하기",
    dadTip: "수문장 교대 시간을 먼저 확인하면 시작부터 몰입도가 달라져요.",
  },
  {
    id: "changdeokgung",
    name: "창덕궁·종묘",
    dataName: "창덕궁·종묘",
    shortName: "창덕궁·종묘",
    district: "종로구",
    lat: 37.5787,
    lng: 126.9934,
    moods: ["탐험하기", "배우기"],
    setting: "야외",
    duration: 4,
    cost: "일부 유료",
    energy: 2,
    learning: 3,
    emoji: "🌿",
    tagline: "궁궐과 숲을 함께 걷는 차분한 역사 탐험",
    mission: "궁궐 건물 지붕 위 동물 장식 개수 세기",
    dadTip: "후원 관람은 별도 예약이 필요할 수 있어 출발 전 확인이 좋아요.",
  },
  {
    id: "ddp",
    name: "DDP 동대문디자인플라자",
    dataName: "DDP(동대문디자인플라자)",
    shortName: "DDP",
    district: "중구",
    lat: 37.567,
    lng: 127.0103,
    moods: ["탐험하기", "배우기"],
    setting: "실내+야외",
    duration: 2,
    cost: "일부 유료",
    energy: 1,
    learning: 2,
    emoji: "🛸",
    tagline: "우주선 같은 건축 안팎을 걷는 디자인 탐사",
    mission: "직선보다 곡선이 더 많이 보이는 이유 상상해보기",
    dadTip: "전시가 없어도 건물 탐방 자체가 재미있고 야간 조명도 훌륭해요.",
  },
  {
    id: "nodeul-island",
    name: "노들섬",
    dataName: "노들섬",
    shortName: "노들섬",
    district: "용산구",
    lat: 37.5176,
    lng: 126.9587,
    moods: ["느긋하게", "탐험하기"],
    setting: "실내+야외",
    duration: 2,
    cost: "무료",
    energy: 1,
    learning: 1,
    emoji: "🎸",
    tagline: "한강 한가운데서 음악과 노을을 즐기는 느슨한 오후",
    mission: "섬에서 보이는 다리와 산의 이름 추측하기",
    dadTip: "공연 일정이 겹치면 분위기는 좋지만 귀가 동선이 붐빌 수 있어요.",
  },
  {
    id: "namsan",
    name: "남산공원",
    dataName: "남산공원",
    shortName: "남산공원",
    district: "중구",
    lat: 37.5516,
    lng: 126.9938,
    moods: ["뛰놀기", "탐험하기"],
    setting: "야외",
    duration: 4,
    cost: "무료",
    energy: 3,
    learning: 2,
    emoji: "⛰️",
    tagline: "도심 한복판에서 성곽길과 전망을 얻는 미니 등산",
    mission: "정상까지 계단 수를 100개 단위로 어림잡기",
    dadTip: "올라갈 때 걷고 내려올 때 버스를 타면 성취감과 체력을 모두 챙겨요.",
  },
  {
    id: "banpo-river",
    name: "반포한강공원",
    dataName: "반포한강공원",
    shortName: "반포한강공원",
    district: "서초구",
    lat: 37.5098,
    lng: 126.9947,
    moods: ["뛰놀기", "느긋하게"],
    setting: "야외",
    duration: 2,
    cost: "무료",
    energy: 2,
    learning: 1,
    emoji: "🌉",
    tagline: "다리 아래 그늘과 야경이 있어 저녁 나들이에 강한 곳",
    mission: "잠수교 위에서 차·자전거·배 세 가지 이동수단 찾기",
    dadTip: "여름 한낮보다 해 질 무렵이 훨씬 좋아요. 분수 운영은 미리 확인하세요.",
  },
  {
    id: "yeouido-river",
    name: "여의도한강공원",
    dataName: "여의도한강공원",
    shortName: "여의도한강",
    district: "영등포구",
    lat: 37.529,
    lng: 126.9282,
    moods: ["뛰놀기", "느긋하게"],
    setting: "야외",
    duration: 4,
    cost: "무료",
    energy: 3,
    learning: 1,
    emoji: "🚲",
    tagline: "자전거와 넓은 잔디가 필요한 날의 확실한 선택",
    mission: "강 건너 보이는 가장 높은 건물 세 개 순서 매기기",
    dadTip: "행사일에는 혼잡도가 급상승해요. 여유가 없으면 이촌 쪽으로 바꿔보세요.",
  },
  {
    id: "ttukseom-river",
    name: "뚝섬한강공원",
    dataName: "뚝섬한강공원",
    shortName: "뚝섬한강",
    district: "광진구",
    lat: 37.5292,
    lng: 127.0715,
    moods: ["뛰놀기", "느긋하게"],
    setting: "야외",
    duration: 4,
    cost: "무료",
    energy: 3,
    learning: 1,
    emoji: "🛹",
    tagline: "운동장 같은 한강공원, 몸 쓰고 싶은 4학년에게 딱",
    mission: "자벌레 전망대에서 한강의 흐르는 방향 맞히기",
    dadTip: "수영장 운영 기간이나 주말 저녁은 입구부터 붐빌 수 있어요.",
  },
  {
    id: "boramae",
    name: "보라매공원",
    dataName: "보라매공원",
    shortName: "보라매공원",
    district: "동작구",
    lat: 37.493,
    lng: 126.9201,
    moods: ["뛰놀기", "탐험하기"],
    setting: "야외",
    duration: 2,
    cost: "무료",
    energy: 3,
    learning: 2,
    emoji: "✈️",
    tagline: "비행기 전시와 트랙이 만나는 가벼운 동네 탐험",
    mission: "전시 비행기의 공통점과 차이점 세 가지 찾기",
    dadTip: "2시간만 있어도 알차게 놀 수 있어 갑작스러운 오후 일정에 좋아요.",
  },
  {
    id: "jamsil-stadium",
    name: "잠실종합운동장",
    dataName: "잠실종합운동장",
    shortName: "잠실운동장",
    district: "송파구",
    lat: 37.5145,
    lng: 127.0736,
    moods: ["뛰놀기", "탐험하기"],
    setting: "야외",
    duration: 4,
    cost: "일부 유료",
    energy: 3,
    learning: 1,
    emoji: "⚾",
    tagline: "경기 있는 날엔 응원까지, 없는 날엔 한강과 묶는 스포츠 코스",
    mission: "오늘 경기의 결정적 장면을 한 문장으로 중계해보기",
    dadTip: "경기·공연 종료 시간에는 대중교통이 매우 붐비니 10분 일찍 움직이세요.",
  },
  {
    id: "gocheok",
    name: "고척스카이돔",
    dataName: "고척돔",
    shortName: "고척돔",
    district: "구로구",
    lat: 37.4977,
    lng: 126.867,
    moods: ["뛰놀기", "느긋하게"],
    setting: "실내",
    duration: 4,
    cost: "일부 유료",
    energy: 2,
    learning: 1,
    emoji: "⚾",
    tagline: "날씨 걱정 없이 야구와 응원에 푹 빠지는 날",
    mission: "투수의 공이 포수까지 가는 시간을 마음속으로 재보기",
    dadTip: "행사 없는 날은 볼거리가 적어요. 반드시 경기·행사 일정을 확인하세요.",
  },
  {
    id: "cheonggyesan",
    name: "청계산",
    dataName: "청계산",
    shortName: "청계산",
    district: "서초구",
    lat: 37.4407,
    lng: 127.05,
    moods: ["뛰놀기", "탐험하기"],
    setting: "야외",
    duration: 6,
    cost: "무료",
    energy: 3,
    learning: 2,
    emoji: "🥾",
    tagline: "아빠와 제대로 땀 흘리고 성취감을 얻는 반나절 도전",
    mission: "정상까지 힘들었던 순간과 좋았던 순간 하나씩 말하기",
    dadTip: "정상 욕심보다 아이 속도에 맞춰 매봉 전 쉼터를 반환점으로 잡아도 충분해요.",
  },
];

export const PLACE_BY_DATA_NAME = new Map(
  PLACES.map((place) => [place.dataName, place]),
);

export const LEVEL_SCORE: Record<string, number> = {
  여유: 4,
  보통: 3,
  "약간 붐빔": 2,
  붐빔: 1,
  "확인 중": 2.5,
};

export const LEVEL_COLOR: Record<string, string> = {
  여유: "#1fa97a",
  보통: "#e3a723",
  "약간 붐빔": "#e66c37",
  붐빔: "#d94747",
  "확인 중": "#7b8291",
};
